FROM node:14.9.0-buster-slim as builder

WORKDIR /app
COPY package.json .
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install
COPY . .
RUN npm run build:prod

FROM nginx:1.19.3-alpine

COPY --from=builder /app/dist/ /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
